services:
  web:
    build:
      context: .
      network: host
    ports:
      - "8000:8000"
    depends_on:
      mlflow:
        condition: service_healthy
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - type: bind
        source: ./California-Housing-Price-Prediction/api/templates
        target: /app/api/templates
      - type: bind
        source: ./California-Housing-Price-Prediction/Models
        target: /app/Models
      - type: bind
        source: ./mlruns
        target: /app/mlruns
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.5.0
    ports:
      - "5000:5000"
    environment:
      - BACKEND_STORE_URI=sqlite:///mlflow.db
      - ARTIFACT_ROOT=/mlartifacts
    volumes:
      - ./mlartifacts:/mlartifacts
      - ./mlruns:/mlruns
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
